Адаптивная сетка для страницы каталога
htmlacademy-adaptive/1620049-pink-22 pull request #10
Opened 2021-04-17 13:32 UTC by vryzhkova

2021-04-17 20:09 UTC, andreysgra requested changes
Когда у изображения заданы такие свойства `max-width: 100%; height: auto;` будет увеличиваться и высота изображения, что будет влиять на остальной контент:

![image](https://user-images.githubusercontent.com/17790771/115124843-1dae3400-9fcd-11eb-8eb9-0dadc90e0e12.png)

`height: auto;` стоит заменить на `object-fit: contain`

---

Блок `panorama__author-info` явно лишний. Функции обёртки выполняет `panorama__post-item`. Это замечание к блоку панорамы. Также у меня вызывает вопросы различие в разметке в блоке панорамы и в блоках с остальными фото. В панораме блок имеет такую разметку

![image](https://user-images.githubusercontent.com/17790771/115125023-3a973700-9fce-11eb-903e-5e09f4b253b2.png)

(использован тег `blockquote` и ненужный `div`с классом `panorama__author-info о котором писал выше), а описание других фото размечено без `blockquote`

![image](https://user-images.githubusercontent.com/17790771/115125080-9c57a100-9fce-11eb-9068-fa853bd85908.png)

Смотрится это довольно странно, так как блоки с описанием везде идентичны (в панораме единственно отличие в том, что блок имеет большую ширину. Это всё CSS, то есть оформление, а логика документа - HTML должна быть одинаковой.

Ещё один момент - в ТЗ есть указание на то, что "все изображения являются ссылками на полноразмерный вариант" (пункт 6.1). Значит изображения в галерее нужно обернуть ссылками.

2021-04-17 20:09 UTC, andreysgra commented on source/sass/blocks/filter.scss
> +}
Эти классы должны быть описаны в соответствующих файлах.

2021-04-17 20:09 UTC, andreysgra commented on source/sass/blocks/panorama.scss
> +.gallery__author-wrap {
В файл gallery.scss

2021-04-18 09:13 UTC, vryzhkova commented on source/sass/blocks/filter.scss
> +}
Добавила им приставку filter__, чтобы не путаться в блоках

2021-04-18 09:13 UTC, vryzhkova commented on source/sass/blocks/filter.scss
> +  display: flex;
По поводу object-fit: contain, теперь  картинка не растягивается при увеличении экрана

2021-04-18 13:32 UTC, andreysgra commented on source/sass/blocks/filter.scss
> +  display: flex;
Так у вас пока используется только мобильный вариант картинки. В дальнейшем при выполнении задания по адаптивной графике вы подключите к проекту другие версии картинок.

2021-04-18 13:38 UTC, merged