Разметка страницы каталога
htmlacademy-adaptive/1620049-pink-22 pull request #4
Opened 2021-03-28 11:38 UTC by vryzhkova

2021-03-28 17:25 UTC, andreysgra requested changes

2021-03-28 17:25 UTC, andreysgra commented on source/catalog.html
> +                  <span class="panorama__likes-number">Нравится: 215</span>
Текст "Нравится" можно в `span` не оборачивать, а вот для цифр (количество лайков) `span` рекомендуется, так как этот параметр на рабочем сайте будет изменяться динамически. То есть будет выглядеть так:
```
<button class="panorama__heart" type="button">
  Нравится: <span class="panorama__likes-number">215</span>
</button>
```

2021-03-28 17:25 UTC, andreysgra commented on source/catalog.html
> +            />
Это не просто изображения, это элементы переключения вкладок (на мобильной версии). Так что нужно разметить кнопками.

2021-03-28 17:25 UTC, andreysgra commented on source/catalog.html
> +        <input type="range" id="points" name="points" min="0" max="10" />
Не советую использовать в данном случае `type="range"`, так как его стилизация нетривиальна. Конечно задача вполне решаемая, но для этого уровня вёрстки несколько сложная. Если интересно, то вот хорошая [статья](https://css-tricks.com/sliding-nightmare-understanding-range-input/) на эту тему (на английском). Информацию для IE и Edge можно пропустить, так как сейчас это не актуально.

Лучше разметить с помощью `div`, подобно тому, как верстали на первом уровне фильтр цены. Там было 2 ползунка, а здесь один.

2021-03-28 17:25 UTC, andreysgra commented on source/catalog.html
> +          <button class="button newPost__button-post">Запостить</button>
`type="submit"`, так как есть [этот пункт](https://up.htmlacademy.ru/adaptive/22/project/pink#pink-6-4) ТЗ.

2021-03-28 17:25 UTC, andreysgra commented on source/catalog.html
> +          <button class="button newPost__button-cancel">Отмена</button>
`type="reset"`, так как есть [другой пункт](https://up.htmlacademy.ru/adaptive/22/project/pink#pink-6-5) ТЗ.

2021-03-28 17:25 UTC, andreysgra commented on source/catalog.html
> +        <div class="newPost__button">
Здесь и в кнопках в названии класса есть заглавная буква, что недопустимо.

2021-03-28 17:25 UTC, andreysgra commented on source/catalog.html
> +      <section class="newPost">
В названии класса есть заглавная буква.

2021-03-28 17:25 UTC, andreysgra commented on source/catalog.html
> +        <div class="newPost__wrapper">
В названии класса есть заглавная буква.

2021-03-28 17:25 UTC, andreysgra commented on source/catalog.html
> +          <div class="newPost__tools">
В названии класса есть заглавная буква.

2021-03-28 17:25 UTC, andreysgra commented on source/catalog.html
> +      <section class="newPost">
Теперь то, что касается всего этого блока:

![image](https://user-images.githubusercontent.com/17790771/112761194-cdae0400-9002-11eb-9cd6-9139c9be4150.png)

Так как у нас есть кнопка отправки данных ("запостить"), перед нами ни что иное, как форма. Значит нужно разметить её тегом `form`.

Вот эту часть формы

![image](https://user-images.githubusercontent.com/17790771/112761236-14036300-9003-11eb-80b7-e8cb2fe438dc.png)

нужно разметить с помощью `input type=""file`. Элемент скроем с помощью класса `visually-hidden`, так как стилизовать его в соответствии с макетом не получится, а картинку разместим в теге `label`. Поскольку `label` будет связан с `input type=""file` по `id`, то клик по картинке откроет окно загрузки файла (встроенная в браузер функциональность).

2021-03-29 15:22 UTC, andreysgra requested changes

2021-03-29 15:22 UTC, andreysgra commented on source/catalog.html
> +            <label for="form-file"
Метку нужно привязать к соответствующему полю. Связка производится с помощью атрибута `for`. Значение `for` должно совпадать со значением `id` поля. У поля `id="form-file"`, значит метке добавляем `for="form-file"`.

2021-03-29 15:22 UTC, andreysgra commented on source/catalog.html
> +              />:</label
Текста у метки нет, но для доступности нужно добавить скрытый текст:
```
<label for="form-file"><span class="visually-hidden">Выберите фотографию</span></label>
```
Кстати, внутри метки изображение можно сделать фоновым.

2021-03-29 15:22 UTC, andreysgra commented on source/catalog.html
> +              <button class="button filter__button-cancel" type="button">
```suggestion
              <button class="button filter__button-cancel" type="reset">
```
Так, как это кнопка сброса параметров.

2021-03-29 18:42 UTC, vryzhkova commented on source/catalog.html
> +            <label for="form-file"
Вроде бы совпадает id у input и for у label

```
<label for="form-file"><span class="visually-hidden">Выберите фотографию</span></label>
<input
  class="visually-hidden filter__form-file"
  type="file"
  id="form-file"
  name="form-file"
/>
```

2021-03-29 20:10 UTC, merged