Адаптивная сетка для страницы формы
htmlacademy-adaptive/1620049-pink-22 pull request #9
Opened 2021-04-13 14:24 UTC by vryzhkova

2021-04-13 18:40 UTC, andreysgra requested changes
А почему у блоков `success` и `failed` ширина 460px? В мобильной версии она равна 280px, в планшетной 460px и в десктопной 780px.

---

Здесь явная ошибка:

![image](https://user-images.githubusercontent.com/17790771/114602940-d27be480-9c9f-11eb-9424-76bf1157f016.png)

есть общий блок `contest` который выполняет функцию контейнера (у него класс `container`), но вложенные в него блоки почему-то тоже имеют данный класс. Вложенные блоки выходят за пределы контейнера:

![image](https://user-images.githubusercontent.com/17790771/114603291-39999900-9ca0-11eb-9c09-58c627236586.png)

Классы, которые подчеркнул красным цветом нужно удалить.

---

В планшетной версии порядок блоков не соответствует макету (можно использовать `flex` для формы и блоки перестроить с помощью свойства `order`).

---

В десктопной версии порядок блоков и ширина некоторых блоков не соответствует макету.

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +  background-image: url("../../img/table/icon-yes.svg");
```suggestion
  background-image: url("../img/table/icon-yes.svg");
```

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +  background-image: url("../../img/table/icon-no.svg");
```suggestion
  background-image: url("../img/table/icon-no.svg");
```

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/contest-title.scss
> +  }
Элемент `contest__title` должен находиться в файле **contest.scss** (файл **contest-title.scss** для блока `contest-title` и его элементов, которых у вас нет).

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/contest.scss
> +}
В файл **contest-title-win.scss**.

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/form.scss
> +}
В файл **contest-title-win.scss**.

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/header.scss
>  //     height: 729px;
Переименуйте файл в **page-header.scss** (здесь блок `page-header` и его элементы).

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/page.scss
> +
В **page-header.scss**.

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/page.scss
> +  }
В **page-header.scss**.

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/page.scss
> +  }
В **page-header.scss**.

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +
В **global.scss**

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +}
В **price.scss**

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
>  }
В **price.scss**

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +}
В **table-price.scss**

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +  background-image: url("../../img/table/icon-yes.svg");
В **table-price.scss**

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +  }
В **table-price.scss**

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +  }
В **global.scss**

2021-04-13 18:40 UTC, andreysgra commented on source/form.html
> +    <div class="failed container">
Это модальное окно, зачем ему класс `container`? Модальное окно позиционируется поверх остального контента и ему не нужен класс `container` который ограничивает ширину контента.

2021-04-13 18:40 UTC, andreysgra commented on source/form.html
> +    <div class="success container">
Не нужен класс `container`

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +}
У вас есть класс `page__body`, зачем для тега `body` писать те же самые свойства?

![image](https://user-images.githubusercontent.com/17790771/114602219-0571a880-9c9f-11eb-9f7c-9d63718f9771.png)

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +}
Есть класс `container` с теми же самыми свойствами. Зачем создавать ещё один?

2021-04-13 18:40 UTC, andreysgra commented on source/sass/blocks/contest-title.scss
>    height: 171px;
Фиксированная высота. Убрать.

2021-04-14 14:17 UTC, vryzhkova commented on source/sass/blocks/price-table.scss
> +  background-image: url("../../img/table/icon-yes.svg");
Не совсем понимаю, в чем тут проблема 😞 
Размеры иконок как и в макете.

2021-04-14 14:21 UTC, vryzhkova commented on source/sass/blocks/price-table.scss
> +  background-image: url("../../img/table/icon-yes.svg");
По поводу 2 комментария - убрать классы container. Теперь на мобильной версии серый фон вложен в контейнер и не растягивается на всю ширину. Как это исправить?

2021-04-14 17:40 UTC, andreysgra commented on source/sass/blocks/contest.scss
> +  }
В **contest-title-win.scss**

2021-04-14 17:40 UTC, andreysgra commented on source/sass/blocks/form.scss
>  .form__achievement-list__item {
`.form__achievement-list__item` - элемент элемента (ошибка БЭМ). Должно быть так `.form__achievement-list-item`

2021-04-14 17:40 UTC, andreysgra commented on source/form.html
> +                  <li class="form__achievement-list__item">
```suggestion
                  <li class="form__achievement-list-item">
```

2021-04-14 17:40 UTC, andreysgra commented on source/form.html
> +                  <li class="form__achievement-list__item">
```suggestion
                  <li class="form__achievement-list-item">
```

2021-04-14 17:40 UTC, andreysgra commented on source/form.html
> +                  <li class="form__achievement-list__item">
```suggestion
                  <li class="form__achievement-list-item">
```

2021-04-14 17:40 UTC, andreysgra commented on source/form.html
> +                  <li class="form__achievement-list__item">
```suggestion
                  <li class="form__achievement-list-item">
```

2021-04-14 17:40 UTC, andreysgra commented on source/form.html
> +                  <li class="form__achievement-list__item">
```suggestion
                  <li class="form__achievement-list-item">
```

2021-04-14 17:40 UTC, andreysgra commented on source/form.html
> +                  <li class="form__achievement-list__item">
```suggestion
                  <li class="form__achievement-list-item">
```

2021-04-14 17:40 UTC, andreysgra commented on source/form.html
> +                  <li class="form__application-list__item">
```suggestion
                  <li class="form__achievement-list-item">
```

2021-04-14 17:40 UTC, andreysgra commented on source/form.html
> +                  <li class="form__application-list__item">
```suggestion
                  <li class="form__achievement-list-item">
```

2021-04-14 17:40 UTC, andreysgra commented on source/form.html
> +                  <li class="form__application-list__item">
```suggestion
                  <li class="form__achievement-list-item">
```

2021-04-14 17:40 UTC, andreysgra commented on source/sass/blocks/form.scss
> +  }
В **contest-title-win.scss**

2021-04-14 17:40 UTC, andreysgra commented on source/sass/blocks/page-footer.scss
>    }
В **social.scss**.

2021-04-14 17:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +// @media (min-width: $tablet-width) {
Так как не могу написать замечание к конкретной строке кода, то пишу здесь. Этот класс

![image](https://user-images.githubusercontent.com/17790771/114751767-3ebd1d80-9d5e-11eb-8981-1b51d42c20da.png)

в файл **price.scss**.

2021-04-14 17:40 UTC, andreysgra commented on source/sass/blocks/price-table.scss
> +  background-image: url("../../img/table/icon-yes.svg");
Я на этот момент сразу не обратил внимания, что в мобильной версии в двух блоках есть серый фон. Исправить ситуацию нужно так: отказаться от общего контейнера-секции с классами `contest container` (container ограничивает ширину и не даёт фону тянуться на всю ширину экрана).

Для каждой группы элементов формы (fieldset) нужно сделать блок-обёртку и там где нужно добавить в неё серый фон. fieldset'ам добавить класс `container`.

Кстати, эти поля

![image](https://user-images.githubusercontent.com/17790771/114754791-a0cb5200-9d61-11eb-8724-f861b18c465b.png)

тоже стоит обернуть в `fieldset`, так как это группа полей.

2021-04-15 17:33 UTC, merged